apiVersion: infra.trigui.com/v1alpha1
kind: EC2Instance
metadata:
  labels:
    app.kubernetes.io/name: ec2-operator
    app.kubernetes.io/managed-by: kustomize
  name: ec2instance-sample
spec:
  # TODO(user): Add fields here
  region: eu-west-3
  amiId: ami-09593e6f738a812d5
  instanceType: t3.micro